version: "2"
linters:
  enable:
    - cyclop
    - funlen
    - gocognit
  settings:
    cyclop:
      max-complexity: 12
    funlen:
      lines: 100
      statements: 50
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
